spring:
  http:
    client:
      connect-timeout: 20s
      read-timeout: 10m
  profiles:
    active: local
  aop:
    auto: true
    proxy-target-class: true
  application:
    name: freshrss_news_upload
  datasource:
    url: jdbc:postgresql://183.87.45.129:5432/freshrss
    username: freshrss
    password: freshrss
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  ai:
    openai:
      base-url: ${LLM_URL}
      api-key: ${LLM_KEY}
      chat:
        options:
          model: deepseek/deepseek-v3.2
          temperature: 0.2

ai:
  relevance:
    model: deepseek/deepseek-v3.2
    temperature: 0.1
    countAttempts: 10
    relevance-threshold: 4
  translating:
    translatingStage:
      temperature: 0.2
      countAttempts: 10
      model: deepseek/deepseek-v3.2
    normalizationStage:
      temperature: 0.1
      countAttempts: 10
      model: deepseek/deepseek-v3.2
    formattingStage:
      model: deepseek/deepseek-v3.2
      temperature: 0.1
      countAttempts: 10
  cleaning:
    removingHtml:
      temperature: 0.1
      countAttempts: 10
      model: deepseek/deepseek-v3.2
    removingNoise:
      temperature: 0.1
      countAttempts: 10
      model: deepseek/deepseek-v3.2
    normalization:
      temperature: 0.2
      countAttempts: 10
      model: deepseek/deepseek-v3.2
  digest:
    batch-size: 50
    log-dir: /usr1/logs/llm
    ranking-model: deepseek/deepseek-v3.2
    ranking-temperature: 0.1
    ranking-thread-pool-size: 20
    ranking-timeout: 60000
    summary-model: deepseek/deepseek-v3.2
    summary-temperature: 0.4
    summary-thread-pool-size: 5
    summary-timeout: 120000
    translation-model: deepseek/deepseek-v3.2
    translation-temperature: 0.2
    translation-thread-pool-size: 15
    translation-timeout: 30000

logging:
  level:
    org.springframework.ai.retry.autoconfigure.*: ERROR
server:
  servlet:
    context-path: /api
  port: 8888

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

cloud:
  windowSize: 7
  directories:
    category: category
    feed: feed
    articles: articles
    news_summary: news_summary

  file-name: report.json
  base-path-files: ${BASE_PATH_CLOUD}
