spring:
  http:
    client:
      connect-timeout: 20s
      read-timeout: 10m
  profiles:
    active: local
  aop:
    auto: true
    proxy-target-class: true
  application:
    name: freshrss_news_upload
  datasource:
    url: jdbc:postgresql://183.87.45.129:5432/freshrss
    username: freshrss
    password: freshrss
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  ai:
    openai:
      base-url: ${LLM_URL}
      api-key: ${LLM_KEY}
      chat:
        options:
          model: deepseek/deepseek-v3.2
          temperature: 0.2

ai:
  relevance:
    model: deepseek/deepseek-v3.2
    temperature: 0.1
    countAttempts: 10
    relevance-threshold: 4
  translating:
    stages:
      - stageName: TRANSLATION_STAGE
        temperature: 0.2
        countAttempts: 10
        model: deepseek/deepseek-v3.2
        systemPromptPathEn: prompt/translations/translation-prompt-en.txt
        systemPromptPathZh: prompt/translations/translation-prompt-zh.txt
        userPromptPath: prompt/user-prompt.txt
        validation:
          temperature: 0.1
          countAttempts: 3
          model: deepseek/deepseek-v3.2
          systemPromptPathEn: prompt/translations/translation-validation-prompt-en.txt
          systemPromptPathZh: prompt/translations/translation-validation-prompt-zh.txt
          userPromptPath: prompt/translations/user-prompt-validation.txt
      - stageName: NORMALIZATION_STAGE
        temperature: 0.1
        countAttempts: 10
        model: deepseek/deepseek-v3.2
        systemPromptPathEn: prompt/translations/normalization-prompt-en.txt
        systemPromptPathZh: prompt/translations/normalization-prompt-zh.txt
        userPromptPath: prompt/user-prompt.txt
      - stageName: FORMATTING_STAGE
        model: deepseek/deepseek-v3.2
        temperature: 0.1
        countAttempts: 10
        systemPromptPathEn: prompt/translations/formatting-prompt.txt
        systemPromptPathZh: prompt/translations/formatting-prompt.txt
        userPromptPath: prompt/user-prompt.txt
  cleaning:
    stages:
      - stageName: CLEANING_STAGE
        temperature: 0.1
        countAttempts: 10
        model: deepseek/deepseek-v3.2
        systemPromptPath: prompt/cleaning/cleaning-prompt.txt
        userPromptPath: prompt/user-prompt.txt
      - stageName: NOISE_REMOVING_STAGE
        temperature: 0.1
        countAttempts: 10
        model: deepseek/deepseek-v3.2
        systemPromptPath: prompt/cleaning/noise-removing-prompt.txt
        userPromptPath: prompt/user-prompt.txt
        validation:
          temperature: 0.1
          countAttempts: 3
          model: deepseek/deepseek-v3.2
          systemPromptPath: prompt/cleaning/cleaning-validation-prompt.txt
          userPromptPath: prompt/cleaning/user-prompt-validation.txt
      - stageName: NORMALIZATION_STAGE
        temperature: 0.2
        countAttempts: 10
        model: deepseek/deepseek-v3.2
        systemPromptPath: prompt/cleaning/normalization-prompt.txt
        userPromptPath: prompt/user-prompt.txt
  digest:
    batch-size: 50
    log-dir: /usr1/logs/llm
    ranking-model: deepseek/deepseek-v3.2
    ranking-temperature: 0.1
    ranking-thread-pool-size: 20
    ranking-timeout: 60000
    summary-model: deepseek/deepseek-v3.2
    summary-temperature: 0.4
    summary-thread-pool-size: 5
    summary-timeout: 120000
    translation-model: deepseek/deepseek-v3.2
    translation-temperature: 0.2
    translation-thread-pool-size: 15
    translation-timeout: 30000

logging:
  level:
    org.springframework.ai.retry.autoconfigure.*: ERROR
server:
  servlet:
    context-path: /api
  port: 8888

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

cloud:
  windowSize: 7
  directories:
    category: category
    feed: feed
    articles: articles
    news_summary: news_summary

  file-name: report.json
  base-path-files: ${BASE_PATH_CLOUD}
