spring:
  http:
    client:
      connect-timeout: 20s
      read-timeout: 5m
  profiles:
    active: local
  aop:
    auto: true
    proxy-target-class: true
  application:
    name: freshrss_news_upload
  datasource:
    url: jdbc:postgresql://183.87.45.129:5432/freshrss
    username: freshrss
    password: freshrss
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      base-url: ${LLM_URL}
      api-key: ${LLM_KEY}
      chat:
        options:
          model: deepseek/deepseek-v3.2
          temperature: 0.2

ai:
  translating:
    temperature: 0.2
    countAttempts: 10
  cleaning:
    temperature: 0.1
    countAttempts: 10
  processing:
    timeout: 1200000
    batch-size: 50
    thread-pool-size: 5
    log-dir: /usr1/logs/llm
    ranking-model: deepseek/deepseek-v3.2
    ranking-temperature: 0.1
    summary-model: deepseek/deepseek-v3.2
    summary-temperature: 0.4
  scraper:
    timeout: 15000
    user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    max-content-length: 20000

logging:
  level:
    org.springframework.ai.retry.autoconfigure.*: ERROR
server:
  servlet:
    context-path: /api
  port: 8888

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

cloud:
  directories:
    category: category
    feed: feed
    articles: articles
    news_summary: news_summary

  file-name: report.json
  base-path-files: ${BASE_PATH_CLOUD}
